max_execution_time = 300

; Maximum amount of time each script may spend parsing request data
max_input_time = 600

; Maximum amount of memory a script may consume
memory_limit = 256M

; Maximum size of POST data that PHP will accept
post_max_size = 64M

; Maximum allowed size for uploaded files
upload_max_filesize = 64M